### ISSUE TITLE
Mimikko Characters have the wrong gender

### ISSUE THREAD

**Issue by templeofshadow** [MycophobiaSC/mimikko_tl#1]
My mod version, as reported by `mod_info.json`, is `0.661`.

I noticed that in some interactions, the pronouns would be wrong (e.g. "he", "him", etc.). 
I tracked down some config files in my various folders (`Starsector/mods/Mimikko Assistants/data/config/chatter/characters/*`, `Starsector/saves/[save]/campaign.xml`, and assumedly anywhere else in the files where the character descriptors are mentioned), and noticed that the gender descriptor was wrong.

For example, in `Starsector/mods/Mimikko Assistants/data/config/chatter/characters/Mimikko_ariana.json`:

`{"name": "Ariana",
    "personalities": ["steady", "aggressive", "reckless","cautious"],
    "gender": [ 
        "m", # <= here
    ],
    "chance": 0,
    "talkativeness": 0.65,
    "categoryTags": [
        "othermedia",
    ],
}`

This seems to be an issue in all instances of all Mimikko characters that I've checked.
I'm unsure if this is on purpose or accident, or perhaps a translation error, but I figured I should post an issue just in case it wasn't noticed.

**Comment by MycophobiaSC** [comment]
I had actually assumed that this to be on purpose by author as an inside joke (since most mimikko interaction does not use gender strings so I wasnt sure if the gender will even matter), and didn't bother with it.

I have spoken to the author and it seems it is indeed an oversight on his part, I have changed the add officer script in source code which hopefully correct the issue in the interim

**Comment by templeofshadow** [comment]
Gotcha. Thanks for the speedy fix.
